[tox]
isolated_build = True

[testenv]
deps =
    -r requirements.txt
allowlist_externals =
    make
    echo
commands =
    make html

[testenv:py313-linkcheck]
commands =
    make html
    make linkcheck

[testenv:py313-livehtml]
commands =
    make livehtml
