#!/bin/bash
# 
#  Written by Deniz to get round the problem that license sharing causes with coupled problems.
# It copies into users .ansys directory a license preferences file that stops sharing of licenses
#
#
if [ -z $ANSYSROOT ] ; then
   echo " Please use 'module load apps/ansys' command first "
   exit 1
fi

if [ $# != 1 ] ; then
  echo -e "\n Usage:   ansyscoupling [on/off] \n "
elif [ "$1" == "on" -o "$1" == "ON" -o "$1" == "1" ] ; then
   mkdir -p $HOME/.ansys/v${ANSYSVER}/licensing
   cp /usr/local/packages6/ansys/sheffield/license.coupling.xml $HOME/.ansys/v${ANSYSVER}/licensing/license.preferences.xml
   echo " Ansys coupling is turned on. "
elif  [ "$1" == "off" -o "$1" == "OFF" -o "$1" == 0 ] ; then 
    mkdir -p $HOME/.ansys/v${ANSYSVER}/licensing
   cp /usr/local/packages6/ansys/sheffield/license.research.xml $HOME/.ansys/v${ANSYSVER}/licensing/license.preferences.xml
   echo " Ansys coupling is turned off. "
else
  echo " Please specify off  or  on " 
fi

 
