#!/bin/bash
# added a forced setting of the lm license file variable
#
if [ -z $ANSYSROOT ] ; then
   echo " Please use 'module load apps/ansys' command first "
   exit 1
fi

# point to the license file. Needed
export FLUENTLM_LICENSE_FILE=1055@ansyslm.shef.ac.uk

# Inherited from a working script from version v6.3 
# particularly the last line about browser fixes help html viewing problems.

export FLUENT_INC=${ANSYSROOT}/fluent
export PATH=$FLUENT_INC/bin:$PATH
export FLUENT_ARCH=lnamd64
export FLUENT_HELP_BROWSER=mozilla

$FLUENT_INC/bin/fluent -g  $*
 
