#!/bin/bash
# added a forced setting of the lm license file variable
#
if [ -z $ANSYSROOT ] ; then
   echo " Please use 'module load apps/ansys' command first "
   exit 1
fi

# point to the license file. Needed
export FLUENTLM_LICENSE_FILE=1055@ansyslm.shef.ac.uk

export FLUENT_INC=${ANSYSROOT}/fluent
export FLUENT_ARCH=lnamd64
export FLUENT_HELP_BROWSER=mozilla

$FLUENT_INC/bin/fluent $*
 
