#!/bin/bash
# added a forced setting of the lm license file variable
#
if [ -z $ANSYSROOT ] ; then
   echo " Please use 'module load apps/ansys' command first "
   exit 1
fi

#  The below two lines fixes problems about academic vs commercial license issues.
  mkdir -p $HOME/.ansys/v${ANSYSVER}/licensing
# copy the research licenses XML file ( for license preferences) 
  cp /usr/local/packages6/ansys/sheffield/license.teaching.xml $HOME/.ansys/v${ANSYSVER}/licensing/license.preferences.xml
# point to the license file.
## export FLUENTLM_LICENSE_FILE=1055@ansyslm.shef.ac.uk

export FLUENT_INC=${ANSYSROOT}/fluent
export FLUENT_ARCH=lnamd64
export FLUENT_HELP_BROWSER=mozilla

$FLUENT_INC/bin/fluent $*
# copy back the research file XML..
#
cp /usr/local/packages6/ansys/sheffield/license.research.xml $HOME/.ansys/v${ANSYSVER}/licensing/license.preferences.xml
 
