#!/bin/bash
#
# invoked by runfluent14 shell script.
# If you move or modify this file you must make sure 
# that runfluent14 command still works as it need this script
# at the specified location. 
#
# Join error and default output channels ...
#$  -j y
#  D.S. 

#  The below two lines fixes problems about academic vs commercial license issues.
mkdir -p $HOME/.ansys/v145/licensing
cp /usr/local/packages6/ansys/sheffield/license.research.xml $HOME/.ansys/v145/licensing/license.preferences.xml
module load apps/ansys/14.5
export TMPDIR=/scratch
export FLUENT_INC=/usr/local/packages6/ansys/ansys_inc/v145/fluent
export FLUENT_ARCH=lnamd64
export DISPLAY=NULL
export TIMECOUNTER=0
source timeused
#
$FLUENT_INC/bin/fluent $*
#
timeused

