#!/bin/bash
## 
#Record the use of this script by Stuart Mumford.
# logger -p local1.debug "iceberg_software: USER=$USER TYPE=monitor SOFTWARE=/usr/local/bin/abaqus"
#DS straight link will not work 
#  
export XLIB_SKIP_ARGB_VISUALS=1
mesa=" "
if [ "$1" == "cae" ] ;then
    mesa="-mesa"
fi
if [ -z $ABAQUSCOMMAND ] ; then
   echo " Please use 'module load apps/abaqus' command first "
   exit 1
fi
# Load the correct version of the compiler... 
 module load compilers/${ABAQCOMPVER} 
#debug info:  module list
 $ABAQUSCOMMAND $* $mesa

