#!/bin/bash
#  D.S.     June.09  
#  Modified August.11 & August 2012 , August 2015
gethosts()
{
#  echo $*
hostlist='['
while [ $# -gt 0 ]
 do
hostlist=${hostlist}'['${1/.iceberg.shef.ac.uk/}','$2']' 
shift
shift
 done
hostlist=${hostlist}']' 

}

source  /etc/profile.d/modules.sh
module load apps/abaqus/612
# 
#  In case user subroutines are used we need to make the intel compiler available
#
module load compilers/intel/11.0
export DISPLAY=NULL
# the below line is a temporary fix to avoid filestore
# limitations on the /tmp area on workers ( only 3GB )
export TMPDIR=/fastdata/$USER
export TIMECOUNTER=0

#
# cater for parallel jobs
# 
if test -r "$PE_HOSTFILE" ; then
          echo " Assuming it to be a parallel job."
            gethosts `cut  -f 1-2 -d \  $PE_HOSTFILE`
            echo $hostlist
            export mp_host_list=$hostlist
       else
           echo "This job is running on a serial queue."
           hostlist=' '
       fi


#
source timeused
#
echo " Abaqus Parameters in use are:  $* " 

${ABAQUSCOMMAND} $*

timeused


