#!/bin/bash
#
# This is a hack to replace [abaqus doc] command that does not seem to work  
#  By Deniz on February 2017
#  
if [ "$ABAQUSVER" == "611" ] ;then
   echo " Loading Abaqus Documentation .... "
   firefox file:///usr/local/packages5/abaqus/Documentation/docs/v6.11/index.html

elif [ "$ABAQUSVER" == "613" ] ;then 
   echo " Loading Abaqus Documentation .... "
   firefox file:///usr/local/packages6/abaqus/Documentation/docs/v6.13/index.html
elif [ "$ABAQUSVER" == "612" ] ;then 
   echo " Sorry there is no Abaqus Documentation on iceberg for V6.12.... "
#   firefox file:///usr/local/packages6/abaqus/Documentation/docs/v6.13/index.html
  echo " However, there is documentation for the other versions. "

elif [ "$ABAQUSVER" == "614" ] ;then
  echo " Loading Abaqus Documentation .... "
  firefox file:///usr/local/packages6/abaqus/Documentation/614/Documentation/docs/v6.14/index.html
fi
 

